#!/usr/bin/env node

const { spawn } = require('child_process');
let cloud9;

if (process.platform === 'win32') {

	var rl = require('readline').createInterface({
		input: process.stdin,
		output: process.stdout
	});

	rl.on('SIGINT', function () {
		process.emit('SIGINT');
	});
	
}

process.on('SIGINT', function () {
	cloud9.kill('SIGHUP');
});

cloud9 = spawn('node', [
	'./cloud9/server.js',
	'--listen',
	'0.0.0.0',
	'--port',
	'80',
	'-w',
	'/root',
	'-b'
]);

cloud9.stdout.on('data', (data) => {
	console.log(data.toString('utf8'));
});

cloud9.stderr.on('data', (data) => {
	console.log(data.toString('utf8'));
});

cloud9.on('close', (code) => {
	process.exit(code);
});